### ISSUE TITLE
Is there a backend?

### ISSUE THREAD

**Issue by xnf4o** [thenaim/ion-tk-social-network#1]
Interested

UPD. Понял что ты русский, уж больно много схожестей с вк)

**Comment by thenaim** [comment]
@xnf4o,

1. No plan yet about backend, but in future versions will be implemented.
2. Yes, i am building an VK clone with all native functionality on ionic.

Ps: Сама идея заключается в том чтобы создать копию вк на ionic и использовать как стартер в дальнейшем. Я не вижу тут ничего такого и я бы не сказал что есть много схожести с вк, так как сам вк копирует тот же инстаграм, тикток и тд.
